services:
  - type: web
    name: askeva-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: rasa run --enable-api --cors "*" --debug
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
